name: NEURON Documentation

on:
  push:
    branches:
      - master
      - live-debug*
      - release/**
  pull_request:
    branches:
      - master
      - release/**

jobs:
  documentation:
    runs-on: ubuntu-18.04

    name: Documentation

    timeout-minutes: 20

    steps:

      - name: documentation
        run: |
          exit 0
        shell: bash


  ci:
    runs-on: ubuntu-18.04
    needs: documentation
    steps:
      - name: Exit with success
        run: exit 0
        
  WindowsInstaller:
    runs-on: ubuntu-18.04
    needs: documentation
    steps:
      - name: Exit with success
        run: exit 0
